# SPDX-License-Identifier: LGPL-2.1-or-later

[Config]
MinimumVersion=26

[Distribution]
Distribution=custom

[Build]
CacheDirectory=mkosi.cache
Incremental=true
ToolsTree=default
History=true

[Output]
Format=disk
ImageId=TimelessOS
OutputDirectory=mkosi.output
SplitArtifacts=yes

[Content]
# MKOSI 25.3 does not currently support this. Wait until MKOSI Updates.
# Splash=/usr/share/plymouth/themes/spinner/watermark.png
CleanPackageMetadata=no
SourceDateEpoch=0
KernelCommandLine=
	rw
KernelModulesInitrdExclude=.*
KernelModulesInitrdInclude=
	default
	plymouth
	crypto
	tpm2-tss
UnifiedKernelImageFormat=%i_%v_%a
UnifiedKernelImages=yes

[Validation]
SecureBoot=yes
SignExpectedPcr=yes

[Runtime]
RuntimeSize=32G
RAM=8G
CPUs=4
Ephemeral=yes
RuntimeScratch=no
TPM=yes
