# Unique project name
name: meowmeowlinux

# Required BuildStream version
min-version: 2.7

# Subdirectory where elements are stored
element-path: elements

ref-storage: project.refs

fatal-warnings:
# - overlaps
  - ref-not-in-track
  - unaliased-url

aliases:
  (@): include/aliases.yml

variables:
  bootstrap-prefix: /tools
  bootstrap-sysconfdir: "%{bootstrap-prefix}/etc"
  bootstrap-localstatedir: "%{bootstrap-prefix}/var"

  triplet: x86_64-meowmeow-linux-gnu
  bootstrap-sysroot: /sysroot

  sbindir: "%{bindir}"

  strip-binaries: ""

sources:
  gnu:
    config:
      mirror: "gnu-ftp:/gnu/"

plugins:
  - origin: junction
    junction: plugins/bst-plugins.bst
    elements:
      - meson
      - autotools
      - make
      - cmake
      - pip
      - setuptools
    sources:
      - patch
      - git
      - pip
  - origin: junction
    junction: plugins/bst-plugins-community.bst
    elements:
      - cargo
    sources:
      - ostree
      - git_tag
      - git_repo
      - patch_queue
      - pypi
  - origin: local
    path: plugins/
    sources:
      - gnu
