# Unique project name
name: meowmeowlinux

# Required BuildStream version
min-version: 2.7

# Subdirectory where elements are stored
element-path: elements

ref-storage: project.refs

fatal-warnings:
  - overlaps
  - ref-not-in-track
  - unaliased-url

aliases:
  (@): include/aliases.yml

plugins:
  - origin: junction
    junction: plugins/bst-plugins.bst
    elements:
      - meson
      - autotools
      - cmake
      - pip
      - setuptools
    sources:
      - git
      - pip
  - origin: junction
    junction: plugins/bst-plugins-community.bst
    elements:
      - cargo
    sources:
      - ostree
      - git_tag
      - git_repo
      - pypi
