kind: stack

depends:
  - bootstrap/stage1/gcc.bst
  - bootstrap/stage1/binutils.bst
  - bootstrap/stage1/glibc.bst
  - bootstrap/stage1/bash.bst
  - bootstrap/stage1/gawk.bst
  - bootstrap/stage1/ncurses.bst
  - bootstrap/stage1/coreutils.bst
  - bootstrap/stage1/sed.bst
  - bootstrap/stage1/acl.bst
  - bootstrap/stage1/attr.bst
  - bootstrap/stage1/zstd.bst
  - bootstrap/stage1/grep.bst
  - bootstrap/stage1/pcre2.bst
  - bootstrap/stage1/linux-headers.bst
  - bootstrap/stage1/readline.bst
  - bootstrap/stage1/make.bst
  - bootstrap/stage1/diffutils.bst
  - bootstrap/stage1/tar.bst
  - bootstrap/fs.bst
